### ISSUE TITLE
Module '"lyr-ix"' has no exported member 'ActionsHandle'

### ISSUE THREAD

**Issue by Tamashi-Dake** [bouzidanas/lyr-ix#5]
![image](https://github.com/bouzidanas/lyr-ix/assets/87293433/14cee36a-f5e0-49b7-a493-e692edfed30d)
somehow when I use `npm install bouzidanas/lyr-ix ` to install and follow `<LyrixCard>` component in [`src/components/LyrixCard.js`](https://github.com/bouzidanas/lyr-ix/blob/master/src/components/LyrixCard.tsx) It's missing:
```
export type ActionsHandle = {
    play: () => void;
    pause: () => void;
    isPlaying: () => boolean;
  }
```
but in node-module: 
![image](https://github.com/bouzidanas/lyr-ix/assets/87293433/ef4f8355-868b-474d-b9f9-6c4ef7039d5f)

Although adding it solves the problem but it won't work in production. Can you have a check on it again?

**Comment by bouzidanas** [comment]
As you noted, it is missing from `index.ts` and thus isnt seen as something you can import from the package. 

I will add it now.  Thanks for making me aware!

**Comment by bouzidanas** [comment]
This issue should be resolved now. I tested the changes and was able to import `ActionsHandle`. Before I close this, let me know if the issue dissappears on your end once you `npm uninstall lyr-ix` and then reinstall it ( `npm install bouzidanas/lyr-ix` )

**Comment by Tamashi-Dake** [comment]
great, problem with node module is now solved.

btw how can i contact with you later cus i having some questions about this repository.

**Comment by bouzidanas** [comment]
Hi @Tamashi-Dake 

Thank you for the feedback. Very much appreciated. I will consider this issue closed.

If you have questions unrelated to any issue, you can contact me using my email listed on my profile: [anas.bouzid@bezda.net](mailto:anas.bouzid@bezda.net)
